# Generated by Django 3.0.6 on 2022-10-18 18:47

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('application', '0004_auto_20221016_2033'),
    ]

    operations = [
        migrations.RenameField(
            model_name='shippingaddress',
            old_name='oder',
            new_name='order',
        ),
        migrations.RemoveField(
            model_name='shippingaddress',
            name='state',
        ),
    ]
